# Generated by Django 3.0.5 on 2020-06-05 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('nationality', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='')),
                ('alt_no', models.IntegerField()),
                ('father_no', models.IntegerField()),
                ('mother_no', models.IntegerField()),
                ('perm_address', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('father_occupation', models.CharField(max_length=30)),
                ('mother_occupation', models.CharField(max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
