# Generated by Django 3.0.5 on 2020-07-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('deposite', models.DecimalField(decimal_places=2, max_digits=7)),
                ('withdrawal', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=15)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institute_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='institute_info/default.jpg', upload_to='institute_info')),
                ('slogan', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('alt_contact', models.CharField(max_length=10, null=True)),
                ('website', models.URLField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('rules', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminFunc.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('nationality', models.CharField(max_length=20)),
                ('img', models.ImageField(default='student_profile/default.jpg', upload_to='student_profile')),
                ('alt_no', models.CharField(blank=True, max_length=10, null=True)),
                ('father_no', models.CharField(max_length=10)),
                ('mother_no', models.CharField(max_length=10)),
                ('perm_address', models.CharField(max_length=70)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=30, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('in_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminFunc.Classes')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=10)),
                ('alt_ph', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField()),
                ('specialization', models.CharField(max_length=50)),
                ('emp_type', models.CharField(max_length=13)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('nationality', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('img', models.ImageField(default='teacher_profile/default.jpg', upload_to='teacher_profile')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
