# Generated by Django 3.0.5 on 2020-06-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminFunc', '0002_auto_20200606_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('alt_ph', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('specialization', models.CharField(max_length=30)),
                ('emp_type', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
