# Generated by Django 3.0.5 on 2020-07-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0003_auto_20200713_0441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
