# Generated by Django 3.0.5 on 2020-07-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0005_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'student')},
        ),
    ]
