# Generated by Django 3.0.5 on 2020-07-13 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0006_auto_20200713_0600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Student_Attendance',
        ),
        migrations.CreateModel(
            name='Employee_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminFunc.Employee_Details')),
            ],
            options={
                'unique_together': {('date', 'employee')},
            },
        ),
    ]
