# Generated by Django 3.0.5 on 2020-06-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0007_auto_20200610_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
