# Generated by Django 3.0.5 on 2020-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0008_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
