# Generated by Django 3.0.5 on 2020-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0009_auto_20200610_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='img',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='img',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
