# Generated by Django 3.0.5 on 2020-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0010_auto_20200612_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('alt_contact', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('rules', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='img',
            field=models.ImageField(default='teacher_profile/default.jpg', upload_to='teacher_profile'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='img',
            field=models.ImageField(default='student_profile/default.jpg', upload_to='student_profile'),
        ),
    ]
