# Generated by Django 3.0.5 on 2020-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0011_auto_20200617_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_info',
            name='slogan',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
