# Generated by Django 3.0.5 on 2020-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0012_institute_info_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='alt_ph',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institute_info',
            name='alt_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institute_info',
            name='logo',
            field=models.ImageField(default='institute_info/default.jpg', upload_to='institute_info'),
        ),
    ]
