# Generated by Django 3.0.5 on 2020-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFunc', '0013_auto_20200624_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('deposite', models.DecimalField(decimal_places=2, max_digits=7)),
                ('withdrawal', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
